name: Synthetic Test
run-name: Synthetic Test

on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "25.8.1"
      - name: Test
        run: yarn ci:install && yarn ci:test
